PINYIN_TABLE = {
    '阿': 'a',
    '埃': 'ai', '爱': 'ai', '矮': 'ai', '艾': 'ai',
    '安': 'an', '岸': 'an', '案': 'an', '胺': 'an',
    '凹': 'ao', '奥': 'ao', '奧': 'ao', '澳': 'ao',
    '八': 'ba', '巴': 'ba',
    '拜': 'bai', '柏': 'bai', '白': 'bai', '百': 'bai',
    '办': 'ban', '半': 'ban', '斑': 'ban', '板': 'ban', '版': 'ban', '班': 'ban',
    '邦': 'bang',
    '保': 'bao', '堡': 'bao', '宝': 'bao', '薄': 'bao',
    '北': 'bei', '卑': 'bei', '备': 'bei', '背': 'bei', '贝': 'bei',
    '本': 'ben',
    '壁': 'bi', '比': 'bi', '毕': 'bi', '碧': 'bi',
    '变': 'bian', '编': 'bian', '边': 'bian',
    '标': 'biao', '表': 'biao',
    '别': 'bie',
    '槟': 'bin',
    '並': 'bing', '冰': 'bing', '并': 'bing',
    '伯': 'bo', '博': 'bo', '波': 'bo', '玻': 'bo', '箔': 'bo', '簸': 'bo', '铂': 'bo',
    '不': 'bu', '布': 'bu', '部': 'bu',
    '彩': 'cai', '材': 'cai',
    '餐': 'can',
    '沧': 'cang', '滄': 'cang',
    '槽': 'cao', '糙': 'cao', '草': 'cao',
    '册': 'ce', '策': 'ce',
    '层': 'ceng',
    '茶': 'cha', '诧': 'cha',
    '产': 'chan',
    '厂': 'chang', '场': 'chang', '常': 'chang',
    '朝': 'chao', '超': 'chao',
    '晨': 'chen', '沉': 'chen', '辰': 'chen',
    '乘': 'cheng', '城': 'cheng', '橙': 'cheng', '称': 'cheng', '程': 'cheng',
    '尺': 'chi', '翅': 'chi', '赤': 'chi',
    '抽': 'chou',
    '储': 'chu', '厨': 'chu', '础': 'chu',
    '传': 'chuan', '川': 'chuan',
    '创': 'chuang', '創': 'chuang', '窗': 'chuang',
    '春': 'chun', '纯': 'chun',
    '次': 'ci', '瓷': 'ci', '磁': 'ci',
    '粗': 'cu',
    '翠': 'cui',
    '存': 'cun', '寸': 'cun',
    '大': 'da', '打': 'da', '搭': 'da', '达': 'da',
    '代': 'dai', '带': 'dai', '黛': 'dai',
    '丹': 'dan', '单': 'dan', '淡': 'dan',
    '当': 'dang',
    '刀': 'dao', '道': 'dao',
    '德': 'de', '的': 'de',
    '灯': 'deng', '登': 'deng',
    '低': 'di', '地': 'di', '帝': 'di', '廸': 'di', '第': 'di', '蒂': 'di', '迪': 'di',
    '典': 'dian', '店': 'dian', '点': 'dian', '电': 'dian', '颠': 'dian',
    '吊': 'diao', '调': 'diao', '雕': 'diao',
    '蝶': 'die',
    '丁': 'ding', '定': 'ding', '订': 'ding', '顶': 'ding',
    '东': 'dong', '冬': 'dong', '洞': 'dong',
    '豆': 'dou', '都': 'dou',
    '度': 'du', '杜': 'du', '肚': 'du',
    '短': 'duan', '端': 'duan', '缎': 'duan',
    '对': 'dui',
    '敦': 'dun', '顿': 'dun',
    '多': 'duo',
    '俄': 'e', '鹅': 'e',
    '恩': 'en',
    '二': 'er', '尔': 'er', '耳': 'er',
    '发': 'fa', '法': 'fa',
    '反': 'fan', '梵': 'fan', '范': 'fan',
    '仿': 'fang', '房': 'fang', '放': 'fang', '方': 'fang', '芳': 'fang',
    '啡': 'fei', '妃': 'fei', '斐': 'fei', '翡': 'fei', '菲': 'fei', '费': 'fei', '非': 'fei',
    '分': 'fen', '粉': 'fen', '芬': 'fen',
    '凤': 'feng', '峰': 'feng', '枫': 'feng', '缝': 'feng', '蜂': 'feng', '风': 'feng',
    '佛': 'fu', '副': 'fu', '复': 'fu', '夫': 'fu', '服': 'fu', '浮': 'fu', '福': 'fu', '芙': 'fu',
    '改': 'gai', '概': 'gai',
    '干': 'gan',
    '岗': 'gang', '港': 'gang', '钢': 'gang',
    '高': 'gao',
    '各': 'ge', '哥': 'ge', '格': 'ge', '歌': 'ge', '革': 'ge', '鸽': 'ge',
    '根': 'gen',
    '供': 'gong', '公': 'gong', '宫': 'gong', '工': 'gong', '拱': 'gong',
    '古': 'gu', '谷': 'gu', '骨': 'gu',
    '刮': 'gua', '挂': 'gua',
    '关': 'guan', '观': 'guan', '馆': 'guan',
    '光': 'guang', '广': 'guang',
    '柜': 'gui', '桂': 'gui', '瑰': 'gui', '硅': 'gui', '规': 'gui', '贵': 'gui',
    '丨': 'gun',
    '国': 'guo', '果': 'guo', '过': 'guo',
    '哈': 'ha',
    '海': 'hai',
    '寒': 'han', '汉': 'han',
    '号': 'hao', '好': 'hao', '浩': 'hao',
    '合': 'he', '和': 'he', '河': 'he', '荷': 'he', '褐': 'he',
    '黑': 'hei',
    '很': 'hen', '痕': 'hen',
    '横': 'heng',
    '红': 'hong', '虹': 'hong', '鸿': 'hong',
    '厚': 'hou', '后': 'hou',
    '弧': 'hu', '户': 'hu', '湖': 'hu', '狐': 'hu', '琥': 'hu', '瑚': 'hu', '胡': 'hu', '虎': 'hu',
    '划': 'hua', '化': 'hua', '华': 'hua', '滑': 'hua', '画': 'hua', '畫': 'hua', '花': 'hua',
    '幻': 'huan', '环': 'huan',
    '凰': 'huang', '皇': 'huang', '黄': 'huang',
    '会': 'hui', '卉': 'hui', '灰': 'hui', '绘': 'hui', '辉': 'hui',
    '昏': 'hun', '混': 'hun',
    '活': 'huo', '火': 'huo', '霍': 'huo',
    '几': 'ji', '及': 'ji', '圾': 'ji', '基': 'ji', '季': 'ji', '寂': 'ji', '技': 'ji', '机': 'ji', '极': 'ji', '济': 'ji', '矶': 'ji', '級': 'ji', '级': 'ji', '纪': 'ji', '肌': 'ji', '计': 'ji', '际': 'ji', '集': 'ji', '鸡': 'ji',
    '佳': 'jia', '加': 'jia', '夹': 'jia', '家': 'jia',
    '件': 'jian', '建': 'jian', '渐': 'jian', '简': 'jian', '间': 'jian',
    '匠': 'jiang', '江': 'jiang', '浆': 'jiang', '降': 'jiang',
    '礁': 'jiao', '胶': 'jiao', '脚': 'jiao', '角': 'jiao',
    '介': 'jie', '界': 'jie', '节': 'jie',
    '津': 'jin', '进': 'jin', '金': 'jin', '锦': 'jin',
    '京': 'jing', '净': 'jing', '境': 'jing', '惊': 'jing', '景': 'jing', '晶': 'jing', '精': 'jing', '镜': 'jing', '静': 'jing',
    '九': 'jiu', '旧': 'jiu', '究': 'jiu', '酒': 'jiu',
    '具': 'ju', '剧': 'ju', '局': 'ju', '居': 'ju', '榉': 'ju', '菊': 'ju',
    '爵': 'jue',
    '军': 'jun', '菌': 'jun',
    '卡': 'ka', '咖': 'ka',
    '凯': 'kai', '开': 'kai',
    '康': 'kang', '抗': 'kang',
    '拷': 'kao', '烤': 'kao',
    '克': 'ke', '刻': 'ke', '可': 'ke', '客': 'ke', '柯': 'ke', '科': 'ke', '课': 'ke',
    '肯': 'ken',
    '坑': 'keng',
    '孔': 'kong', '空': 'kong',
    '口': 'kou', '蔻': 'kou',
    '库': 'ku', '酷': 'ku',
    '跨': 'kua',
    '块': 'kuai',
    '款': 'kuan',
    '框': 'kuang',
    '昆': 'kun',
    '垃': 'la', '拉': 'la', '腊': 'la',
    '莱': 'lai',
    '兰': 'lan', '蓝': 'lan', '藍': 'lan',
    '朗': 'lang', '浪': 'lang',
    '劳': 'lao', '勞': 'lao', '老': 'lao',
    '类': 'lei', '雷': 'lei',
    '冷': 'leng',
    '丽': 'li', '利': 'li', '力': 'li', '栗': 'li', '梨': 'li', '沥': 'li', '理': 'li', '璃': 'li', '砾': 'li', '立': 'li', '粒': 'li', '莉': 'li', '里': 'li',
    '廉': 'lian', '连': 'lian',
    '亮': 'liang', '梁': 'liang',
    '料': 'liao',
    '列': 'lie', '烈': 'lie',
    '林': 'lin',
    '凌': 'ling', '玲': 'ling', '菱': 'ling',
    '六': 'liu', '柳': 'liu', '流': 'liu', '鎏': 'liu',
    '珑': 'long', '瓏': 'long', '胧': 'long', '龙': 'long',
    '楼': 'lou',
    '卢': 'lu', '路': 'lu', '露': 'lu', '魯': 'lu', '鲁': 'lu', '鹭': 'lu',
    '乱': 'luan',
    '伦': 'lun', '倫': 'lun',
    '洛': 'luo', '络': 'luo', '罗': 'luo', '羅': 'luo', '落': 'luo', '裸': 'luo',
    '綠': 'lv', '绿': 'lv',
    '玛': 'ma', '瑪': 'ma', '馬': 'ma', '马': 'ma', '麻': 'ma',
    '脉': 'mai', '麦': 'mai',
    '曼': 'man', '满': 'man', '漫': 'man',
    '毛': 'mao', '猫': 'mao',
    '梅': 'mei', '玫': 'mei', '美': 'mei', '魅': 'mei',
    '门': 'men',
    '孟': 'meng', '朦': 'meng', '梦': 'meng', '檬': 'meng', '蒙': 'meng',
    '秘': 'mi', '米': 'mi', '蜜': 'mi', '迷': 'mi',
    '免': 'mian', '棉': 'mian', '面': 'mian',
    '名': 'ming', '明': 'ming',
    '墨': 'mo', '摩': 'mo', '模': 'mo', '漠': 'mo', '磨': 'mo', '膜': 'mo', '莫': 'mo', '默': 'mo',
    '姆': 'mu', '慕': 'mu', '暮': 'mu', '木': 'mu', '母': 'mu',
    '娜': 'na', '拿': 'na', '纳': 'na', '那': 'na',
    '奶': 'nai', '耐': 'nai',
    '南': 'nan', '楠': 'nan',
    '瑙': 'nao', '脑': 'nao',
    '内': 'nei',
    '妮': 'ni', '尼': 'ni', '拟': 'ni', '泥': 'ni',
    '年': 'nian', '念': 'nian',
    '鸟': 'niao',
    '凝': 'ning', '柠': 'ning',
    '纽': 'niu',
    '浓': 'nong',
    '努': 'nu',
    '暖': 'nuan',
    '挪': 'nuo', '諾': 'nuo', '诺': 'nuo',
    '欧': 'ou', '殴': 'ou', '藕': 'ou',
    '帕': 'pa',
    '拍': 'pai', '牌': 'pai',
    '潘': 'pan',
    '抛': 'pao',
    '佩': 'pei', '裴': 'pei', '配': 'pei',
    '喷': 'pen',
    '朋': 'peng',
    '皮': 'pi',
    '偏': 'pian', '片': 'pian',
    '漂': 'piao', '飘': 'piao',
    '品': 'pin', '拼': 'pin', '频': 'pin',
    '平': 'ping', '瓶': 'ping',
    '泼': 'po', '珀': 'po', '破': 'po',
    '剖': 'pou',
    '普': 'pu', '蒲': 'pu', '铺': 'pu',
    '七': 'qi', '其': 'qi', '器': 'qi', '奇': 'qi', '漆': 'qi', '绮': 'qi', '齐': 'qi',
    '前': 'qian', '千': 'qian', '浅': 'qian', '淺': 'qian',
    '墙': 'qiang', '强': 'qiang',
    '乔': 'qiao', '俏': 'qiao',
    '切': 'qie',
    '琴': 'qin',
    '情': 'qing', '清': 'qing', '轻': 'qing', '青': 'qing',
    '楸': 'qiu', '秋': 'qiu',
    '区': 'qu', '曲': 'qu',
    '全': 'quan', '圈': 'quan',
    '缺': 'que', '雀': 'que',
    '染': 'ran', '然': 'ran',
    '热': 're',
    '人': 'ren',
    '仍': 'reng',
    '日': 'ri',
    '绒': 'rong',
    '柔': 'rou',
    '入': 'ru', '如': 'ru',
    '软': 'ruan',
    '瑞': 'rui',
    '润': 'run',
    '撒': 'sa', '萨': 'sa', '薩': 'sa',
    '塞': 'sai', '赛': 'sai',
    '三': 'san',
    '桑': 'sang',
    '瑟': 'se', '色': 'se',
    '森': 'sen',
    '沙': 'sha', '砂': 'sha', '莎': 'sha',
    '山': 'shan', '珊': 'shan', '衫': 'shan', '闪': 'shan',
    '上': 'shang', '商': 'shang', '尚': 'shang',
    '烧': 'shao', '绍': 'shao', '邵': 'shao',
    '奢': 'she', '射': 'she', '舍': 'she', '设': 'she',
    '深': 'shen', '燊': 'shen', '神': 'shen', '绅': 'shen',
    '圣': 'sheng', '生': 'sheng',
    '世': 'shi', '仕': 'shi', '使': 'shi', '十': 'shi', '士': 'shi', '实': 'shi', '室': 'shi', '市': 'shi', '式': 'shi', '施': 'shi', '时': 'shi', '時': 'shi', '石': 'shi', '示': 'shi', '视': 'shi', '诗': 'shi', '适': 'shi', '饰': 'shi',
    '手': 'shou', '收': 'shou',
    '书': 'shu', '墅': 'shu', '属': 'shu', '术': 'shu', '树': 'shu', '殊': 'shu', '熟': 'shu', '疏': 'shu', '竖': 'shu', '鼠': 'shu',
    '双': 'shuang',
    '水': 'shui',
    '烁': 'shuo', '说': 'shuo',
    '丝': 'si', '四': 'si', '思': 'si', '斯': 'si', '絲': 'si',
    '松': 'song',
    '塑': 'su', '素': 'su', '苏': 'su',
    '算': 'suan',
    '岁': 'sui', '碎': 'sui', '邃': 'sui',
    '损': 'sun',
    '索': 'suo',
    '他': 'ta', '塔': 'ta',
    '台': 'tai', '太': 'tai', '态': 'tai', '汰': 'tai', '钛': 'tai',
    '探': 'tan', '檀': 'tan', '毯': 'tan', '滩': 'tan', '炭': 'tan',
    '堂': 'tang', '棠': 'tang', '糖': 'tang',
    '套': 'tao', '桃': 'tao', '淘': 'tao', '陶': 'tao',
    '特': 'te',
    '藤': 'teng',
    '体': 'ti', '梯': 'ti', '瑅': 'ti', '缇': 'ti', '题': 'ti',
    '天': 'tian',
    '条': 'tiao',
    '贴': 'tie', '铁': 'tie',
    '厅': 'ting', '庭': 'ting',
    '通': 'tong', '铜': 'tong',
    '头': 'tou', '透': 'tou',
    '凸': 'tu', '图': 'tu', '土': 'tu', '突': 'tu',
    '推': 'tui',
    '托': 'tuo', '驼': 'tuo',
    '瓦': 'wa',
    '外': 'wai',
    '万': 'wan', '湾': 'wan',
    '旺': 'wang', '王': 'wang', '网': 'wang',
    '为': 'wei', '卫': 'wei', '唯': 'wei', '威': 'wei', '尾': 'wei', '微': 'wei', '未': 'wei', '维': 'wei', '韦': 'wei', '魏': 'wei',
    '文': 'wen', '紋': 'wen', '纹': 'wen',
    '卧': 'wo', '沃': 'wo',
    '乌': 'wu', '五': 'wu', '务': 'wu', '午': 'wu', '无': 'wu', '武': 'wu', '物': 'wu', '雾': 'wu', '霧': 'wu',
    '吸': 'xi', '希': 'xi', '惜': 'xi', '洗': 'xi', '系': 'xi', '細': 'xi', '细': 'xi', '西': 'xi', '锡': 'xi',
    '下': 'xia', '夏': 'xia', '峡': 'xia',
    '仙': 'xian', '现': 'xian', '线': 'xian', '闲': 'xian', '限': 'xian',
    '像': 'xiang', '橡': 'xiang', '祥': 'xiang', '箱': 'xiang', '象': 'xiang', '项': 'xiang', '香': 'xiang',
    '小': 'xiao', '效': 'xiao', '晓': 'xiao', '销': 'xiao',
    '写': 'xie',
    '信': 'xin', '新': 'xin', '芯': 'xin',
    '型': 'xing', '形': 'xing', '星': 'xing', '杏': 'xing',
    '熊': 'xiong',
    '休': 'xiu', '修': 'xiu', '銹': 'xiu', '锈': 'xiu',
    '序': 'xu',
    '宣': 'xuan', '玄': 'xuan', '轩': 'xuan', '选': 'xuan',
    '学': 'xue', '雪': 'xue',
    '循': 'xun', '熏': 'xun', '逊': 'xun',
    '亚': 'ya', '亞': 'ya', '压': 'ya', '哑': 'ya', '牙': 'ya', '雅': 'ya',
    '岩': 'yan', '演': 'yan', '烟': 'yan', '盐': 'yan', '眼': 'yan', '研': 'yan', '颜': 'yan',
    '洋': 'yang', '阳': 'yang',
    '腰': 'yao',
    '业': 'ye', '叶': 'ye', '耶': 'ye', '野': 'ye', '页': 'ye',
    '一': 'yi', '以': 'yi', '伊': 'yi', '异': 'yi', '意': 'yi', '易': 'yi', '移': 'yi', '绎': 'yi', '翼': 'yi', '艺': 'yi', '衣': 'yi', '议': 'yi', '逸': 'yi',
    '印': 'yin', '殷': 'yin', '銀': 'yin', '银': 'yin',
    '应': 'ying', '影': 'ying', '樱': 'ying', '英': 'ying',
    '用': 'yong',
    '友': 'you', '右': 'you', '尤': 'you', '有': 'you', '油': 'you', '釉': 'you',
    '域': 'yu', '愉': 'yu', '浴': 'yu', '玉': 'yu', '羽': 'yu', '萸': 'yu', '语': 'yu', '郁': 'yu', '雨': 'yu', '预': 'yu', '魚': 'yu', '鱼': 'yu',
    '元': 'yuan', '原': 'yuan', '园': 'yuan', '圆': 'yuan', '远': 'yuan', '院': 'yuan',
    '悦': 'yue', '月': 'yue', '约': 'yue', '越': 'yue',
    '云': 'yun', '运': 'yun',
    '杂': 'za',
    '再': 'zai', '载': 'zai',
    '脏': 'zang',
    '噪': 'zao', '藻': 'zao',
    '增': 'zeng',
    '扎': 'zha',
    '斋': 'zhai', '窄': 'zhai',
    '占': 'zhan',
    '张': 'zhang', '樟': 'zhang', '长': 'zhang',
    '照': 'zhao',
    '折': 'zhe', '浙': 'zhe', '赭': 'zhe',
    '榛': 'zhen', '珍': 'zhen', '臻': 'zhen', '镇': 'zhen',
    '整': 'zheng', '正': 'zheng',
    '之': 'zhi', '制': 'zhi', '志': 'zhi', '智': 'zhi', '直': 'zhi', '纸': 'zhi', '织': 'zhi', '脂': 'zhi', '至': 'zhi', '致': 'zhi', '质': 'zhi',
    '中': 'zhong',
    '宙': 'zhou', '洲': 'zhou',
    '主': 'zhu', '柱': 'zhu', '珠': 'zhu', '竹': 'zhu', '茱': 'zhu',
    '专': 'zhuan', '砖': 'zhuan', '转': 'zhuan',
    '装': 'zhuang',
    '追': 'zhui',
    '准': 'zhun',
    '浊': 'zhuo',
    '兹': 'zi', '子': 'zi', '字': 'zi', '紫': 'zi', '自': 'zi', '资': 'zi',
    '棕': 'zong', '踪': 'zong',
    '族': 'zu', '组': 'zu',
    '钻': 'zuan',
    '最': 'zui',
    '尊': 'zun',
    '作': 'zuo', '做': 'zuo', '左': 'zuo',
}

